In [1]:
import pandas

# 先设置中文对齐
pandas.set_option('display.unicode.ambiguous_as_wide', True)
pandas.set_option('display.unicode.east_asian_width', True)


foods_info = pandas.read_csv(r"D:\JupyterNotebook\PythonFile\Pandas\foods_info.csv" , encoding="gbk")
print(foods_info)

    NDB_No                食物名称  水分_(g)  能量_(千卡)  蛋白质_(g)  \
0    10001          黄油(加盐打发)     15.87          717        0.85
1    10002          黄油(无盐打发)     15.87          717        0.85
2    10003              橄榄油黄油      0.24          876        0.28
3    10004                蓝纹奶酪     42.41          353       21.40
4    10005              布里克奶酪     41.11          371       23.24
5    10006            布里恩扎奶酪     48.42          334       20.75
6    10007            卡门贝尔奶酪     51.80          300       19.80
7    10008              葛缕子奶酪     39.28          376       25.18
8    10009                切达奶酪     37.10          406       24.04
9    10010                柴郡奶酪     37.65          387       23.37
10   10011              科尔比奶酪     38.20          394       23.76
11   10012          茅屋奶酪(全脂)     79.79           98       11.12
12   10013        茅屋奶酪(低脂1%)     79.64           97       10.69
13   10014        茅屋奶酪(低脂2%)     81.01           72       10.34
14   10015          茅屋奶酪(脱脂)     81.24           81       10.45
15   10016          茅屋奶酪(干酪)     82.48           72       12.39
16   10017                奶油奶酪     54.44          342        5.93
17   10018              埃德姆奶酪     41.56          357       24.99
18   10019                菲达奶酪     55.22          264       14.21
19   10020                火锅奶酪     37.92          389       25.60
20   10021            吉托斯特奶酪     13.44          466        9.65
21   10022                高达奶酪     41.46          356       24.94
22   10023                青纹奶酪     33.19          413       29.81
23   10024                林堡奶酪     48.42          327       20.05
24   10025              蒙特利奶酪     41.01          373       24.48
25   10026    马苏里拉奶酪(低水分)     50.01          300       22.17
26   10027  马苏里拉奶酪(部分脱脂)     48.38          318       21.60
27   10028      马苏里拉奶酪(全脂)     53.78          254       24.26
28   10029              明斯特奶酪     45.54          301       24.58
29   10030            纽沙泰尔奶酪     41.77          368       23.41
30   10031        纽沙泰尔奶油奶酪     63.11          253        9.15
31   10032              帕玛森奶酪     22.65          420       28.42
32   10033              普罗卧干酪     41.26          351       25.58
33   10034    里科塔奶酪(部分脱脂)     71.33          138       11.39
34   10035        里科塔奶酪(全脂)     71.70          174       11.26
35   10036              罗马诺奶酪     30.90          387       31.78
36   10037              罗克福奶酪     39.38          369       21.54
37   10038                瑞士奶酪     37.17          393       26.96
38   10039              鸡胸肉(生)     73.23          165       31.02
39   10040              鸡胸肉(熟)     64.70          165       31.00
40   10041              瘦牛肉(生)     71.50          106       20.20
41   10042              瘦牛肉(熟)     59.30          250       26.30
42   10043              三文鱼(生)     63.40          208       20.40
43   10044              三文鱼(熟)     60.10          206       22.10
44   10045                鸡蛋(生)     76.15          143       12.60
45   10046                鸡蛋(熟)     74.60          155       13.00
46   10047              西兰花(生)     90.90           34        2.80
47   10048              西兰花(熟)     90.20           35        2.90
48   10049                苹果(生)     85.56           52        0.20
49   10050                香蕉(生)     74.91           91        1.10

    总脂肪_(g)  灰分_(g)  碳水化合物_(g)  总膳食纤维_(g)  总糖_(g)  钙_(mg)  \
0        81.11      2.11            0.06             0.0      0.06       24
1        81.11      2.11            0.06             0.0      0.06       24
2        99.48      0.00            0.00             0.0      0.00        4
3        28.74      5.11            2.34             0.0      0.50      528
4        29.68      3.18            2.79             0.0      0.51      674
5        27.68      2.70            0.45             0.0      0.45      184
6        24.26      3.68            0.46             0.0      0.46      388
7        29.20      3.28            3.06             0.0      0.04      673
8        33.82      3.71            1.33             0.0      0.28      675
9        30.60      3.60            4.78             0.0      0.52      643
10       32.11      3.36            2.57             0.0      2.57      685
11        4.30      1.41            3.38             0.0      2.67       83
12        3.85      1.20            4.61             0.2      2.38       53
13        0.29      1.71            6.66             0.0      1.85       53
14        2.27      1.27            4.76             0.0      0.00      111
15        1.02      1.39            2.72             0.0      2.72       61
16       34.24      1.32            4.07             0.0      3.21       98
17       27.80      4.22            1.43             0.0      1.43      731
18       21.28      5.20            4.09             0.0      4.09      493
19       31.14      3.79            1.55             0.0      1.55      550
20       29.51      4.75           42.65             0.0      0.00      400
21       27.44      3.94            2.22             0.0      2.22      700
22       32.34      4.30            0.36             0.0      0.36     1011
23       27.25      3.79            0.49             0.0      0.49      497
24       30.28      3.55            0.68             0.0      0.50      746
25       22.35      3.28            2.19             0.0      1.03      505
26       24.64      2.91            2.47             0.0      1.01      575
27       15.92      3.27            2.77             0.0      1.13      782
28       19.72      3.80            6.36             0.0      2.24      716
29       30.04      3.66            1.12             0.0      1.12      717
30       22.78      1.37            3.59             0.0      3.19      117
31       27.84      7.18           13.91             0.0      0.07     1184
32       26.62      3.73            2.14             0.0      2.14      756
33        3.89      1.46            3.27             0.0      0.98      207
34       12.98      1.56            3.04             0.0      0.27      206
35       26.83      7.75            3.22             0.0      0.27     1064
36       30.64      5.04            2.01             0.0      0.63      563
37       31.04      3.90            1.44             0.0      0.36      791
38        3.57      1.18            0.00             0.0      0.00       11
39        3.60      0.70            0.00             0.0      0.00       11
40        2.30      1.20            0.00             0.0      0.00       10
41       15.40      1.30            0.00             0.0      0.00       12
42       13.40      1.80            0.00             0.0      0.00        9
43       12.70      1.70            0.00             0.0      0.00       10
44        9.90      1.06            0.72             0.0      0.38       50
45       10.60      1.10            0.70             0.0      0.40       56
46        0.40      0.70            6.60             2.6      1.70       47
47        0.40      0.70            6.70             2.7      1.70       48
48        0.20      0.20           12.30             2.4     10.40        6
49        0.30      0.80           22.80             2.6     12.20        5

    铁_(mg)  镁_(mg)  磷_(mg)  钾_(mg)  钠_(mg)  锌_(mg)  铜_(mg)
0      0.02        2       24       24      643     0.09    0.003
1      0.16        2       23       26      659     0.05    0.003
2      0.00        0        0        5        2     0.01    0.000
3      0.31       23      387      256     1146     2.66    0.040
4      0.43       24      451      136      560     2.60    0.030
5      0.50       20      188      152      629     2.38    0.030
6      0.33       20      347      187      842     2.38    0.020
7      0.64       22      490       93       93   690.00    2.940
8      0.16       27      473       76      700     3.43    0.030
9      0.21       21      464       95      700     2.79    0.030
10     0.76       26      457      127      604     3.07    0.030
11     0.07        8      159      104      364     0.40    0.030
12     0.16        7      113       90      344     0.33    0.030
13     0.15       11      190      137      372     0.47    0.030
14     0.13        9      150      125      308     0.51    0.030
15     0.14        5      134       86      406     0.38    0.030
16     0.38        9      106      138      365     0.51    0.020
17     0.44       30      536      188      812     3.75    0.030
18     0.65       19      337       62      917     2.88    0.040
19     0.23       14      346       64      800     3.50    0.030
20     0.52       70      444     1409      600     1.14    0.070
21     0.24       29      546      121      819     3.90    0.030
22     0.17       36      605       81      714     3.90    0.040
23     0.13       21      393      128      800     2.10    0.030
24     0.72       27      444       81      600     3.00    0.030
25     0.44       20      354       76      627     2.92    0.030
26     0.20       21      412       75      710     2.46    0.030
27     0.22       23      463       84      619     2.76    0.030
28     0.23       29      537      131      682     3.61    0.030
29     0.41       27      468      134      628     2.81    0.030
30     0.13       10      138      152      334     0.82    0.020
31     0.49       34      627      180     1804     4.20    0.030
32     0.22       28      546      133      876     3.27    0.030
33     0.17        9      151      105      132     1.11    0.030
34     0.23       10      198      105       84     1.38    0.030
35     0.77       36      760      133     1477     4.43    0.040
36     0.33       23      392       91     1800     2.73    0.040
37     0.17       28      605      111      215     4.71    0.030
38     0.73       29      214      223       74     1.03    0.050
39     0.90       22      198      220       70     1.20    0.040
40     2.20       20      190      310       60     4.80    0.080
41     2.60       22      210      330       65     5.20    0.090
42     0.30       26      200      360       50     0.60    0.100
43     0.40       28      215      380       55     0.70    0.110
44     1.75       12      198      126      142     1.29    0.070
45     1.80       13      205      130      145     1.30    0.070
46     0.73       21       66      316       33     0.41    0.050
47     0.75       22       68      320       34     0.42    0.050
48     0.12        5       11      107        1     0.04    0.030
49     0.26       27       22      358        1     0.15    0.080

In [3]:
foods_first_7 = foods_info.head(7)
print(foods_first_7)
print("-----------------------------------")

foods_last_7 = foods_info.tail(7)
print(foods_last_7)
print("-----------------------------------")

# 输出其中两列
two_columns = ["NDB_No", "食物名称"]
columns = foods_info[two_columns]
print(columns)

   NDB_No        食物名称  水分_(g)  能量_(千卡)  蛋白质_(g)  总脂肪_(g)  \
0   10001  黄油(加盐打发)     15.87          717        0.85       81.11
1   10002  黄油(无盐打发)     15.87          717        0.85       81.11
2   10003      橄榄油黄油      0.24          876        0.28       99.48
3   10004        蓝纹奶酪     42.41          353       21.40       28.74
4   10005      布里克奶酪     41.11          371       23.24       29.68
5   10006    布里恩扎奶酪     48.42          334       20.75       27.68
6   10007    卡门贝尔奶酪     51.80          300       19.80       24.26

   灰分_(g)  碳水化合物_(g)  总膳食纤维_(g)  总糖_(g)  钙_(mg)  铁_(mg)  \
0      2.11            0.06             0.0      0.06       24     0.02
1      2.11            0.06             0.0      0.06       24     0.16
2      0.00            0.00             0.0      0.00        4     0.00
3      5.11            2.34             0.0      0.50      528     0.31
4      3.18            2.79             0.0      0.51      674     0.43
5      2.70            0.45             0.0      0.45      184     0.50
6      3.68            0.46             0.0      0.46      388     0.33

   镁_(mg)  磷_(mg)  钾_(mg)  钠_(mg)  锌_(mg)  铜_(mg)
0        2       24       24      643     0.09    0.003
1        2       23       26      659     0.05    0.003
2        0        0        5        2     0.01    0.000
3       23      387      256     1146     2.66    0.040
4       24      451      136      560     2.60    0.030
5       20      188      152      629     2.38    0.030
6       20      347      187      842     2.38    0.020
-----------------------------------
    NDB_No    食物名称  水分_(g)  能量_(千卡)  蛋白质_(g)  总脂肪_(g)  \
43   10044  三文鱼(熟)     60.10          206        22.1        12.7
44   10045    鸡蛋(生)     76.15          143        12.6         9.9
45   10046    鸡蛋(熟)     74.60          155        13.0        10.6
46   10047  西兰花(生)     90.90           34         2.8         0.4
47   10048  西兰花(熟)     90.20           35         2.9         0.4
48   10049    苹果(生)     85.56           52         0.2         0.2
49   10050    香蕉(生)     74.91           91         1.1         0.3

    灰分_(g)  碳水化合物_(g)  总膳食纤维_(g)  总糖_(g)  钙_(mg)  铁_(mg)  \
43      1.70            0.00             0.0      0.00       10     0.40
44      1.06            0.72             0.0      0.38       50     1.75
45      1.10            0.70             0.0      0.40       56     1.80
46      0.70            6.60             2.6      1.70       47     0.73
47      0.70            6.70             2.7      1.70       48     0.75
48      0.20           12.30             2.4     10.40        6     0.12
49      0.80           22.80             2.6     12.20        5     0.26

    镁_(mg)  磷_(mg)  钾_(mg)  钠_(mg)  锌_(mg)  铜_(mg)
43       28      215      380       55     0.70     0.11
44       12      198      126      142     1.29     0.07
45       13      205      130      145     1.30     0.07
46       21       66      316       33     0.41     0.05
47       22       68      320       34     0.42     0.05
48        5       11      107        1     0.04     0.03
49       27       22      358        1     0.15     0.08
-----------------------------------
    NDB_No                食物名称
0    10001          黄油(加盐打发)
1    10002          黄油(无盐打发)
2    10003              橄榄油黄油
3    10004                蓝纹奶酪
4    10005              布里克奶酪
5    10006            布里恩扎奶酪
6    10007            卡门贝尔奶酪
7    10008              葛缕子奶酪
8    10009                切达奶酪
9    10010                柴郡奶酪
10   10011              科尔比奶酪
11   10012          茅屋奶酪(全脂)
12   10013        茅屋奶酪(低脂1%)
13   10014        茅屋奶酪(低脂2%)
14   10015          茅屋奶酪(脱脂)
15   10016          茅屋奶酪(干酪)
16   10017                奶油奶酪
17   10018              埃德姆奶酪
18   10019                菲达奶酪
19   10020                火锅奶酪
20   10021            吉托斯特奶酪
21   10022                高达奶酪
22   10023                青纹奶酪
23   10024                林堡奶酪
24   10025              蒙特利奶酪
25   10026    马苏里拉奶酪(低水分)
26   10027  马苏里拉奶酪(部分脱脂)
27   10028      马苏里拉奶酪(全脂)
28   10029              明斯特奶酪
29   10030            纽沙泰尔奶酪
30   10031        纽沙泰尔奶油奶酪
31   10032              帕玛森奶酪
32   10033              普罗卧干酪
33   10034    里科塔奶酪(部分脱脂)
34   10035        里科塔奶酪(全脂)
35   10036              罗马诺奶酪
36   10037              罗克福奶酪
37   10038                瑞士奶酪
38   10039              鸡胸肉(生)
39   10040              鸡胸肉(熟)
40   10041              瘦牛肉(生)
41   10042              瘦牛肉(熟)
42   10043              三文鱼(生)
43   10044              三文鱼(熟)
44   10045                鸡蛋(生)
45   10046                鸡蛋(熟)
46   10047              西兰花(生)
47   10048              西兰花(熟)
48   10049                苹果(生)
49   10050                香蕉(生)

In [4]:
col_names = foods_info.columns
print(col_names)

gram_columns = []

for c in col_names:
    if c.endswith("(g)"):
        gram_columns.append(c)
print(gram_columns)
print("-----------------------------------")

gram_df = foods_info[gram_columns]
print(gram_df)

Index(['NDB_No', '食物名称', '水分_(g)', '能量_(千卡)', '蛋白质_(g)',
       '总脂肪_(g)', '灰分_(g)', '碳水化合物_(g)', '总膳食纤维_(g)',
       '总糖_(g)', '钙_(mg)', '铁_(mg)', '镁_(mg)', '磷_(mg)', '钾_(mg)',
       '钠_(mg)', '锌_(mg)', '铜_(mg)'],
      dtype='object')
['水分_(g)', '蛋白质_(g)', '总脂肪_(g)', '灰分_(g)', '碳水化合物_(g)', '总膳食纤维_(g)', '总糖_(g)']
-----------------------------------
    水分_(g)  蛋白质_(g)  总脂肪_(g)  灰分_(g)  碳水化合物_(g)  \
0      15.87        0.85       81.11      2.11            0.06
1      15.87        0.85       81.11      2.11            0.06
2       0.24        0.28       99.48      0.00            0.00
3      42.41       21.40       28.74      5.11            2.34
4      41.11       23.24       29.68      3.18            2.79
5      48.42       20.75       27.68      2.70            0.45
6      51.80       19.80       24.26      3.68            0.46
7      39.28       25.18       29.20      3.28            3.06
8      37.10       24.04       33.82      3.71            1.33
9      37.65       23.37       30.60      3.60            4.78
10     38.20       23.76       32.11      3.36            2.57
11     79.79       11.12        4.30      1.41            3.38
12     79.64       10.69        3.85      1.20            4.61
13     81.01       10.34        0.29      1.71            6.66
14     81.24       10.45        2.27      1.27            4.76
15     82.48       12.39        1.02      1.39            2.72
16     54.44        5.93       34.24      1.32            4.07
17     41.56       24.99       27.80      4.22            1.43
18     55.22       14.21       21.28      5.20            4.09
19     37.92       25.60       31.14      3.79            1.55
20     13.44        9.65       29.51      4.75           42.65
21     41.46       24.94       27.44      3.94            2.22
22     33.19       29.81       32.34      4.30            0.36
23     48.42       20.05       27.25      3.79            0.49
24     41.01       24.48       30.28      3.55            0.68
25     50.01       22.17       22.35      3.28            2.19
26     48.38       21.60       24.64      2.91            2.47
27     53.78       24.26       15.92      3.27            2.77
28     45.54       24.58       19.72      3.80            6.36
29     41.77       23.41       30.04      3.66            1.12
30     63.11        9.15       22.78      1.37            3.59
31     22.65       28.42       27.84      7.18           13.91
32     41.26       25.58       26.62      3.73            2.14
33     71.33       11.39        3.89      1.46            3.27
34     71.70       11.26       12.98      1.56            3.04
35     30.90       31.78       26.83      7.75            3.22
36     39.38       21.54       30.64      5.04            2.01
37     37.17       26.96       31.04      3.90            1.44
38     73.23       31.02        3.57      1.18            0.00
39     64.70       31.00        3.60      0.70            0.00
40     71.50       20.20        2.30      1.20            0.00
41     59.30       26.30       15.40      1.30            0.00
42     63.40       20.40       13.40      1.80            0.00
43     60.10       22.10       12.70      1.70            0.00
44     76.15       12.60        9.90      1.06            0.72
45     74.60       13.00       10.60      1.10            0.70
46     90.90        2.80        0.40      0.70            6.60
47     90.20        2.90        0.40      0.70            6.70
48     85.56        0.20        0.20      0.20           12.30
49     74.91        1.10        0.30      0.80           22.80

    总膳食纤维_(g)  总糖_(g)
0              0.0      0.06
1              0.0      0.06
2              0.0      0.00
3              0.0      0.50
4              0.0      0.51
5              0.0      0.45
6              0.0      0.46
7              0.0      0.04
8              0.0      0.28
9              0.0      0.52
10             0.0      2.57
11             0.0      2.67
12             0.2      2.38
13             0.0      1.85
14             0.0      0.00
15             0.0      2.72
16             0.0      3.21
17             0.0      1.43
18             0.0      4.09
19             0.0      1.55
20             0.0      0.00
21             0.0      2.22
22             0.0      0.36
23             0.0      0.49
24             0.0      0.50
25             0.0      1.03
26             0.0      1.01
27             0.0      1.13
28             0.0      2.24
29             0.0      1.12
30             0.0      3.19
31             0.0      0.07
32             0.0      2.14
33             0.0      0.98
34             0.0      0.27
35             0.0      0.27
36             0.0      0.63
37             0.0      0.36
38             0.0      0.00
39             0.0      0.00
40             0.0      0.00
41             0.0      0.00
42             0.0      0.00
43             0.0      0.00
44             0.0      0.38
45             0.0      0.40
46             2.6      1.70
47             2.7      1.70
48             2.4     10.40
49             2.6     12.20

In [ ]:
print(foods_info["钙_(mg)"])
print("-----------------------------------")

div_1000 = foods_info["钙_(mg)"] / 1000 #直接进行加减乘除
print(div_1000)


for idx, value in enumerate(div_1000):  # 遍历索引和对应的值
    if value > 1:
        print(value)
        print(foods_info.loc[idx, "食物名称"])

0       24
1       24
2        4
3      528
4      674
5      184
6      388
7      673
8      675
9      643
10     685
11      83
12      53
13      53
14     111
15      61
16      98
17     731
18     493
19     550
20     400
21     700
22    1011
23     497
24     746
25     505
26     575
27     782
28     716
29     717
30     117
31    1184
32     756
33     207
34     206
35    1064
36     563
37     791
38      11
39      11
40      10
41      12
42       9
43      10
44      50
45      56
46      47
47      48
48       6
49       5
Name: 钙_(mg), dtype: int64
-----------------------------------
0     0.024
1     0.024
2     0.004
3     0.528
4     0.674
5     0.184
6     0.388
7     0.673
8     0.675
9     0.643
10    0.685
11    0.083
12    0.053
13    0.053
14    0.111
15    0.061
16    0.098
17    0.731
18    0.493
19    0.550
20    0.400
21    0.700
22    1.011
23    0.497
24    0.746
25    0.505
26    0.575
27    0.782
28    0.716
29    0.717
30    0.117
31    1.184
32    0.756
33    0.207
34    0.206
35    1.064
36    0.563
37    0.791
38    0.011
39    0.011
40    0.010
41    0.012
42    0.009
43    0.010
44    0.050
45    0.056
46    0.047
47    0.048
48    0.006
49    0.005
Name: 钙_(mg), dtype: float64
1.011
青纹奶酪
1.184
帕玛森奶酪
1.064
罗马诺奶酪

In [ ]:
import pandas as pd

# .sort_values() 方法对数据进行排序升序
foods_info = pd.read_csv(r"D:\JupyterNotebook\PythonFile\Pandas\foods_info.csv" , encoding = "gbk")
foods_info.sort_values("钙_(mg)" , inplace = True) # inplace = true 直接修改原数据 从小到大的排序
print(foods_info["食物名称"])

2            橄榄油黄油
49           香蕉(生)
48           苹果(生)
42          三文鱼(生)
40          瘦牛肉(生)
43          三文鱼(熟)
38          鸡胸肉(生)
39          鸡胸肉(熟)
41          瘦牛肉(熟)
0         黄油(加盐打发)
1         黄油(无盐打发)
46          西兰花(生)
47          西兰花(熟)
44           鸡蛋(生)
12      茅屋奶酪(低脂1%)
13      茅屋奶酪(低脂2%)
45           鸡蛋(熟)
15        茅屋奶酪(干酪)
11        茅屋奶酪(全脂)
16            奶油奶酪
14        茅屋奶酪(脱脂)
30        纽沙泰尔奶油奶酪
5           布里恩扎奶酪
34       里科塔奶酪(全脂)
33     里科塔奶酪(部分脱脂)
6           卡门贝尔奶酪
20          吉托斯特奶酪
18            菲达奶酪
23            林堡奶酪
25     马苏里拉奶酪(低水分)
3             蓝纹奶酪
19            火锅奶酪
36           罗克福奶酪
26    马苏里拉奶酪(部分脱脂)
9             柴郡奶酪
7            葛缕子奶酪
4            布里克奶酪
8             切达奶酪
10           科尔比奶酪
21            高达奶酪
28           明斯特奶酪
29          纽沙泰尔奶酪
17           埃德姆奶酪
24           蒙特利奶酪
32           普罗卧干酪
27      马苏里拉奶酪(全脂)
37            瑞士奶酪
22            青纹奶酪
35           罗马诺奶酪
31           帕玛森奶酪
Name: 食物名称, dtype: object

In [3]:
# 直接修改原数据 从大到小的排序
foods_info.sort_values("钙_(mg)" , inplace = True , ascending = False)
print(foods_info["食物名称"])

31           帕玛森奶酪
35           罗马诺奶酪
22            青纹奶酪
37            瑞士奶酪
27      马苏里拉奶酪(全脂)
32           普罗卧干酪
24           蒙特利奶酪
17           埃德姆奶酪
29          纽沙泰尔奶酪
28           明斯特奶酪
21            高达奶酪
10           科尔比奶酪
8             切达奶酪
4            布里克奶酪
7            葛缕子奶酪
9             柴郡奶酪
26    马苏里拉奶酪(部分脱脂)
36           罗克福奶酪
19            火锅奶酪
3             蓝纹奶酪
25     马苏里拉奶酪(低水分)
23            林堡奶酪
18            菲达奶酪
20          吉托斯特奶酪
6           卡门贝尔奶酪
33     里科塔奶酪(部分脱脂)
34       里科塔奶酪(全脂)
5           布里恩扎奶酪
30        纽沙泰尔奶油奶酪
14        茅屋奶酪(脱脂)
16            奶油奶酪
11        茅屋奶酪(全脂)
15        茅屋奶酪(干酪)
45           鸡蛋(熟)
12      茅屋奶酪(低脂1%)
13      茅屋奶酪(低脂2%)
44           鸡蛋(生)
47          西兰花(熟)
46          西兰花(生)
0         黄油(加盐打发)
1         黄油(无盐打发)
41          瘦牛肉(熟)
38          鸡胸肉(生)
39          鸡胸肉(熟)
40          瘦牛肉(生)
43          三文鱼(熟)
42          三文鱼(生)
48           苹果(生)
49           香蕉(生)
2            橄榄油黄油
Name: 食物名称, dtype: object

In [2]:
import pandas as pd
import numpy as np

employees_info = pd.read_csv(r"D:\JupyterNotebook\PythonFile\Pandas\employees.csv" , encoding = "gbk")

employees_info

      员工ID  姓名   部门     职位    入职年份    年龄       月薪  城市  学历  等级 性别
0   EMP001  陈明  技术部   后端开发  2020.0  30.0  18500.0  北京  本科   2  男
1   EMP002  刘芳  人事部   招聘专员  2021.0  26.0   9800.0  上海  本科   1  女
2   EMP003  张伟  技术部   前端开发  2020.0  28.0  16800.0  深圳  本科   2  男
3   EMP004  李娜  市场部   营销主管  2019.0  32.0  21000.0  广州  硕士   3  女
4   EMP005  王强  财务部     会计  2022.0  25.0   8900.0  杭州  本科   1  男
5   EMP006  赵静  技术部  测试工程师  2021.0  27.0      NaN  成都  本科   1  女
6   EMP007  黄勇  产品部   产品经理  2018.0  34.0  25000.0  北京  硕士   3  男
7   EMP008  周敏  市场部   销售代表  2023.0  24.0   7600.0  重庆  大专   1  女
8   EMP009  吴浩  技术部  运维工程师     NaN  31.0  15200.0  上海  本科   2  男
9   EMP010  郑丽  人事部   HRBP  2020.0  29.0  12800.0  深圳  本科   2  女
10  EMP011  孙杰  财务部   财务主管  2017.0  35.0  23000.0  广州  硕士   3  男
11  EMP012  马辉  产品部   产品助理  2022.0  26.0  10500.0  杭州  本科   2  男
12  EMP013  胡琳  市场部   销售经理  2018.0  33.0  22500.0  成都  本科   3  男
13  EMP014  朱伟  技术部  大数据开发  2021.0  30.0  19800.0  北京  硕士   2  男
14  EMP015  林燕  行政部   行政专员  2023.0  25.0   6800.0  上海  大专   1  女
15  EMP016  高凯  技术部  移动端开发  2020.0   NaN  17200.0  深圳  本科   2  男
16  EMP017  何琪  财务部     出纳  2022.0  27.0   8500.0  广州  本科   1  男
17  EMP018  罗明  市场部  新媒体运营  2021.0  26.0   9200.0  杭州  本科   1  男
18  EMP019  郭丽  技术部  算法工程师  2019.0  32.0  28000.0  成都  硕士   3  女
19  EMP020  宋强  行政部   行政主管  2018.0  34.0  14500.0  重庆  本科   2  男
20  EMP021  谢芳  产品部   交互设计  2022.0  29.0  13800.0  北京  本科   2  女
21  EMP022  彭浩  技术部   前端开发  2020.0  27.0      NaN  上海  本科   2  男
22  EMP023  任敏  市场部   销售代表  2023.0  23.0   7200.0  深圳  大专   1  女
23  EMP024  袁强  人事部   培训专员  2021.0  28.0  10200.0  广州  本科   2  男
24  EMP025  邓丽  技术部   后端开发     NaN  31.0  18800.0  杭州  本科   2  女
25  EMP026  付伟  财务部   成本会计  2020.0  30.0  11500.0  成都  本科   2  男
26  EMP027  董琪  技术部  测试工程师  2022.0  25.0  12800.0  北京  本科   2  男
27  EMP028  梁明  市场部   营销策划  2021.0  29.0  14200.0  上海  本科   2  男
28  EMP029  石丽  产品部  需求分析师  2018.0  33.0  20500.0  深圳  硕士   3  女
29  EMP030  姚强  行政部     前台  2023.0  22.0   6500.0  广州  大专   1  女

In [3]:
from tabulate import tabulate
print(tabulate(employees_info.head(3), headers='keys', tablefmt="psql"))

print("-----------------------------")

employees_info.tail(4)

+----+----------+--------+--------+----------+------------+--------+--------+--------+--------+--------+--------+
|    | 员工ID   | 姓名   | 部门   | 职位     |   入职年份 |   年龄 |   月薪 | 城市   | 学历   |   等级 | 性别   |
|----+----------+--------+--------+----------+------------+--------+--------+--------+--------+--------+--------|
|  0 | EMP001   | 陈明   | 技术部 | 后端开发 |       2020 |     30 |  18500 | 北京   | 本科   |      2 | 男     |
|  1 | EMP002   | 刘芳   | 人事部 | 招聘专员 |       2021 |     26 |   9800 | 上海   | 本科   |      1 | 女     |
|  2 | EMP003   | 张伟   | 技术部 | 前端开发 |       2020 |     28 |  16800 | 深圳   | 本科   |      2 | 男     |
+----+----------+--------+--------+----------+------------+--------+--------+--------+--------+--------+--------+
-----------------------------

      员工ID  姓名   部门     职位    入职年份    年龄       月薪  城市  学历  等级 性别
26  EMP027  董琪  技术部  测试工程师  2022.0  25.0  12800.0  北京  本科   2  男
27  EMP028  梁明  市场部   营销策划  2021.0  29.0  14200.0  上海  本科   2  男
28  EMP029  石丽  产品部  需求分析师  2018.0  33.0  20500.0  深圳  硕士   3  女
29  EMP030  姚强  行政部     前台  2023.0  22.0   6500.0  广州  大专   1  女

In [46]:
age = employees_info["年龄"]
# print(age[0:20])

age_is_null = pd.isnull(age) # 判断age中哪些值是空值，返回一个布尔类型的Series,True表示对应位置的值是空值，False表示对应位置的值不是空值
print(age_is_null)

age_null_true= age[age_is_null]
print(age_null_true)

age_null_count = len(age_null_true)
print(age_null_count)

age_sum = age.sum()
print(age_sum)

age_mean = age_sum / len(age) # 计算平均值，age_sum是年龄的总和，len(age)是年龄的数量,但是不会忽略空值，导致平均数降低

print(age_mean)

age_mean1 = age.mean() # 直接使用mean()方法计算平均值，mean()方法会自动忽略空值，并计算非空值的平均值
print(age_mean1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: 年龄, dtype: bool
15   NaN
Name: 年龄, dtype: float64
1
831.0
27.7
28.655172413793103

In [43]:
dengji = [1,2,3]
dnegji_of_employees = employees_info["等级"]
money_for_dengji = {}
people_for_dengji = {}
for jibie in dengji:
    dengji_employees_rows = employees_info[dnegji_of_employees == jibie]
    dengji_for_money = dengji_employees_rows["月薪"]
    dengji_money_mean = dengji_for_money.mean()
    money_for_dengji[jibie] = dengji_money_mean
print(money_for_dengji)

print("===========================")

for jibie in dengji:
    dengji_employees_rows = employees_info[dnegji_of_employees ==jibie]
    dengji_of_people = dengji_employees_rows["姓名"]
    people_for_dengji[jibie] = dengji_of_people
print(people_for_dengji)

{1: np.float64(8062.5), 2: np.float64(14757.142857142857), 3: np.float64(23333.333333333332)}
===========================
{1: 1     刘芳
4     王强
5     赵静
7     周敏
14    林燕
16    何琪
17    罗明
22    任敏
29    姚强
Name: 姓名, dtype: object, 2: 0     陈明
2     张伟
8     吴浩
9     郑丽
11    马辉
13    朱伟
15    高凯
19    宋强
20    谢芳
21    彭浩
23    袁强
24    邓丽
25    付伟
26    董琪
27    梁明
Name: 姓名, dtype: object, 3: 3     李娜
6     黄勇
10    孙杰
12    胡琳
18    郭丽
28    石丽
Name: 姓名, dtype: object}

In [4]:
# 数据透视表.pivot_table(value = "需要分析的数值，销售额/薪资/需求量" , index = "按什么分组，比如岗位/性别/城市/" （行分组） ， 
# columns = "按特征分组"（列分组），  aggfunc = "对数据怎么处理，求和/平均值/归一")
from tabulate import tabulate

employees_bumen_money = employees_info.pivot_table(values = "年龄" , index = "性别"   , columns="等级" , aggfunc="mean")
employees_bumen_money
# print(employees_bumen_money.to_markdown())
# print(tabulate(employees_bumen_money , tablefmt="simple" , headers="keys"))

等级     1          2          3
性别
女   24.5  29.666667  32.333333
男   26.0  28.909091  34.000000

In [80]:
employees_people = employees_info.pivot_table(values = ["年龄" , "月薪"] , index = "部门" , columns="入职年份" , aggfunc="mean")

employees_people

         年龄                                                     月薪           \
入职年份 2017.0 2018.0 2019.0     2020.0 2021.0 2022.0 2023.0   2017.0   2018.0
部门
产品部     NaN   33.5    NaN        NaN    NaN   27.5    NaN      NaN  22750.0
人事部     NaN    NaN    NaN  29.000000   27.0    NaN    NaN      NaN      NaN
市场部     NaN   33.0   32.0        NaN   27.5    NaN   23.5      NaN  22500.0
技术部     NaN    NaN   32.0  28.333333   28.5   25.0    NaN      NaN      NaN
行政部     NaN   34.0    NaN        NaN    NaN    NaN   23.5      NaN  14500.0
财务部    35.0    NaN    NaN  30.000000    NaN   26.0    NaN  23000.0      NaN


入职年份   2019.0   2020.0   2021.0   2022.0  2023.0
部门
产品部       NaN      NaN      NaN  12150.0     NaN
人事部       NaN  12800.0  10000.0      NaN     NaN
市场部   21000.0      NaN  11700.0      NaN  7400.0
技术部   28000.0  17500.0  19800.0  12800.0     NaN
行政部       NaN      NaN      NaN      NaN  6650.0
财务部       NaN  11500.0      NaN   8700.0     NaN

In [ ]:
# 删含有缺失值的行列，.dropna(axis = 0(删除行)，1(删除列))[只要含有缺失值就删除] 
#  .dropna(axis =0/1 , thresh = n)[非缺失值的个数大于n时，不删除] 
#  .dropna(axis = , subset = ["age" , "money" , ...]),只要age...列有缺失值，就删除这一行或列，只看subset内的列

dropna_columns = employees_info.dropna(axis = 0)
dropna_columns

# dropna_rows = employees_info.dropna(axis=1 , thresh=3)
# dropna_rows

      员工ID  姓名   部门     职位    入职年份    年龄       月薪  城市  学历  等级 性别
0   EMP001  陈明  技术部   后端开发  2020.0  30.0  18500.0  北京  本科   2  男
1   EMP002  刘芳  人事部   招聘专员  2021.0  26.0   9800.0  上海  本科   1  女
2   EMP003  张伟  技术部   前端开发  2020.0  28.0  16800.0  深圳  本科   2  男
3   EMP004  李娜  市场部   营销主管  2019.0  32.0  21000.0  广州  硕士   3  女
4   EMP005  王强  财务部     会计  2022.0  25.0   8900.0  杭州  本科   1  男
6   EMP007  黄勇  产品部   产品经理  2018.0  34.0  25000.0  北京  硕士   3  男
7   EMP008  周敏  市场部   销售代表  2023.0  24.0   7600.0  重庆  大专   1  女
9   EMP010  郑丽  人事部   HRBP  2020.0  29.0  12800.0  深圳  本科   2  女
10  EMP011  孙杰  财务部   财务主管  2017.0  35.0  23000.0  广州  硕士   3  男
11  EMP012  马辉  产品部   产品助理  2022.0  26.0  10500.0  杭州  本科   2  男
12  EMP013  胡琳  市场部   销售经理  2018.0  33.0  22500.0  成都  本科   3  男
13  EMP014  朱伟  技术部  大数据开发  2021.0  30.0  19800.0  北京  硕士   2  男
14  EMP015  林燕  行政部   行政专员  2023.0  25.0   6800.0  上海  大专   1  女
16  EMP017  何琪  财务部     出纳  2022.0  27.0   8500.0  广州  本科   1  男
17  EMP018  罗明  市场部  新媒体运营  2021.0  26.0   9200.0  杭州  本科   1  男
18  EMP019  郭丽  技术部  算法工程师  2019.0  32.0  28000.0  成都  硕士   3  女
19  EMP020  宋强  行政部   行政主管  2018.0  34.0  14500.0  重庆  本科   2  男
20  EMP021  谢芳  产品部   交互设计  2022.0  29.0  13800.0  北京  本科   2  女
22  EMP023  任敏  市场部   销售代表  2023.0  23.0   7200.0  深圳  大专   1  女
23  EMP024  袁强  人事部   培训专员  2021.0  28.0  10200.0  广州  本科   2  男
25  EMP026  付伟  财务部   成本会计  2020.0  30.0  11500.0  成都  本科   2  男
26  EMP027  董琪  技术部  测试工程师  2022.0  25.0  12800.0  北京  本科   2  男
27  EMP028  梁明  市场部   营销策划  2021.0  29.0  14200.0  上海  本科   2  男
28  EMP029  石丽  产品部  需求分析师  2018.0  33.0  20500.0  深圳  硕士   3  女
29  EMP030  姚强  行政部     前台  2023.0  22.0   6500.0  广州  大专   1  女

In [ ]:
# .sort_values("age" , ascending=false) 降序 ，True升序

new_employees_info = employees_info.sort_values("月薪" , ascending=True)
new_employees_info

      员工ID  姓名   部门     职位    入职年份    年龄       月薪  城市  学历  等级 性别
29  EMP030  姚强  行政部     前台  2023.0  22.0   6500.0  广州  大专   1  女
14  EMP015  林燕  行政部   行政专员  2023.0  25.0   6800.0  上海  大专   1  女
22  EMP023  任敏  市场部   销售代表  2023.0  23.0   7200.0  深圳  大专   1  女
7   EMP008  周敏  市场部   销售代表  2023.0  24.0   7600.0  重庆  大专   1  女
16  EMP017  何琪  财务部     出纳  2022.0  27.0   8500.0  广州  本科   1  男
4   EMP005  王强  财务部     会计  2022.0  25.0   8900.0  杭州  本科   1  男
17  EMP018  罗明  市场部  新媒体运营  2021.0  26.0   9200.0  杭州  本科   1  男
1   EMP002  刘芳  人事部   招聘专员  2021.0  26.0   9800.0  上海  本科   1  女
23  EMP024  袁强  人事部   培训专员  2021.0  28.0  10200.0  广州  本科   2  男
11  EMP012  马辉  产品部   产品助理  2022.0  26.0  10500.0  杭州  本科   2  男
25  EMP026  付伟  财务部   成本会计  2020.0  30.0  11500.0  成都  本科   2  男
26  EMP027  董琪  技术部  测试工程师  2022.0  25.0  12800.0  北京  本科   2  男
9   EMP010  郑丽  人事部   HRBP  2020.0  29.0  12800.0  深圳  本科   2  女
20  EMP021  谢芳  产品部   交互设计  2022.0  29.0  13800.0  北京  本科   2  女
27  EMP028  梁明  市场部   营销策划  2021.0  29.0  14200.0  上海  本科   2  男
19  EMP020  宋强  行政部   行政主管  2018.0  34.0  14500.0  重庆  本科   2  男
8   EMP009  吴浩  技术部  运维工程师     NaN  31.0  15200.0  上海  本科   2  男
2   EMP003  张伟  技术部   前端开发  2020.0  28.0  16800.0  深圳  本科   2  男
15  EMP016  高凯  技术部  移动端开发  2020.0   NaN  17200.0  深圳  本科   2  男
0   EMP001  陈明  技术部   后端开发  2020.0  30.0  18500.0  北京  本科   2  男
24  EMP025  邓丽  技术部   后端开发     NaN  31.0  18800.0  杭州  本科   2  女
13  EMP014  朱伟  技术部  大数据开发  2021.0  30.0  19800.0  北京  硕士   2  男
28  EMP029  石丽  产品部  需求分析师  2018.0  33.0  20500.0  深圳  硕士   3  女
3   EMP004  李娜  市场部   营销主管  2019.0  32.0  21000.0  广州  硕士   3  女
12  EMP013  胡琳  市场部   销售经理  2018.0  33.0  22500.0  成都  本科   3  男
10  EMP011  孙杰  财务部   财务主管  2017.0  35.0  23000.0  广州  硕士   3  男
6   EMP007  黄勇  产品部   产品经理  2018.0  34.0  25000.0  北京  硕士   3  男
18  EMP019  郭丽  技术部  算法工程师  2019.0  32.0  28000.0  成都  硕士   3  女
5   EMP006  赵静  技术部  测试工程师  2021.0  27.0      NaN  成都  本科   1  女
21  EMP022  彭浩  技术部   前端开发  2020.0  27.0      NaN  上海  本科   2  男

In [99]:
# 查询第2到第十个样本
new_employees_info[1:10]

#new_employees_info.head()
#new_employees_info.tail(2)

# 查询第13个样本
new_employees_info.loc[13]

员工ID     EMP014
姓名           朱伟
部门          技术部
职位        大数据开发
入职年份     2021.0
年龄         30.0
月薪      19800.0
城市           北京
学历           硕士
等级            2
性别            男
Name: 13, dtype: object

In [9]:
# 定义函数，第10个数据

def the_tenth_row(columns):
    tenth_item = columns.loc[9]
    return tenth_item

# the_tenth_row(employees_info)


# 文件名.apply(函数)
tenth_row = employees_info.apply(the_tenth_row)

tenth_row

员工ID     EMP010
姓名           郑丽
部门          人事部
职位         HRBP
入职年份     2020.0
年龄         29.0
月薪      12800.0
城市           深圳
学历           本科
等级            2
性别            女
dtype: object

In [11]:
# 缺失值个数

def is_null_count(columns):
    columns_null = pd.isnull(columns)
    null = columns[columns_null]
    return len(null)

# is_null_count(employees_info)


columns_null_count = employees_info.apply(is_null_count)
columns_null_count

员工ID    0
姓名      0
部门      0
职位      0
入职年份    2
年龄      1
月薪      2
城市      0
学历      0
等级      0
性别      0
dtype: int64